FROM golang:1.22.0-alpine

RUN apk add --no-cache gcc musl-dev
RUN addgroup -S mercari && adduser -S trainee -G mercari
# RUN chown -R trainee:mercari /path/to/db

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY /app/main.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/mywebserver


EXPOSE 9000

CMD ["/app/mywebserver"]
