FROM golang:1.22.0-alpine

RUN apk add --no-cache gcc musl-dev
RUN addgroup -S mercari && adduser -S trainee -G mercari
# RUN chown -R trainee:mercari /path/to/db

USER trainee
WORKDIR /app

COPY go.mod .
COPY go.sum .

EXPOSE 9000

CMD ["go", "version"]
